kfEditor:
  configPath: "./sample/KFEditor.ini"
  binPath: ""
  logPath: ""
modPackages:
  path: "C:\\YourPath\\to\\ModPackages"
  output: "C:\\YourPath\\to\\Output"
  packages:
    - YourMod1
    - YourMod2
    - YourMod3
