kfEditor:
  configPath: "./sample/KFEditor.ini"
  binPath: ""
  logPath: ""
modPackages:
  path: "C:\\YourPath\\to\\ModPackages"
  output: "C:\\YourPath\\to\\Output"
  packages:
    - YourMod1
    - YourMod2
    - YourMod3
launchOptions:
  gamePath: "C:/YourPath/to/Game"
  languageForCooking: "int"
  mapName: "KF-SubSynth"
  gameMode: "CombinedCD2.CD_Survival"
  mutators:
    - "FriendlyHUD.FriendlyHUDMutator"
  difficulty: 3
  gameLength: 2
  otherOptions:
